[package]
name = "shader-learning"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
flume = "0.11.1"
pollster = "0.4.0"
rand = "0.8.5"
wgpu = "23.0.1"
