[package]
name = "shader-learning"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
flume = "0.11.1"
pollster = "0.4.0"
wgpu = "23.0.1"
log = "0.4.22"
env_logger = "0.11.6"
xorshift = "0.1.3"
clock_ticks = "0.1.1"
